apiVersion: v1
kind: Service
metadata:
  name: {{ include "grapevine-socket.fullname" . }}
  labels:
    {{- include "grapevine-socket.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "grapevine-socket.selectorLabels" . | nindent 4 }}
