apiVersion: v1
kind: Service
metadata:
  name: {{ include "grapevine-telnet.fullname" . }}
  labels:
    {{- include "grapevine-telnet.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "grapevine-telnet.selectorLabels" . | nindent 4 }}
