apiVersion: v1
kind: Service
metadata:
  name: {{ include "grapevine-web.fullname" . }}
  labels:
    {{- include "grapevine-web.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "grapevine-web.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: phoenix
      protocol: TCP
      name: phoenix

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "grapevine-web.fullname" . }}-headless
  labels:
    {{- include "grapevine-web.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "grapevine-web.selectorLabels" . | nindent 4 }}
