name: Node CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 22.2
        elixir-version: 1.9.4
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential
    - name: Setup elixir
      working-directory: apps/grapevine
      run: |
        mix deps.get
    - name: Setup node
      working-directory: apps/grapevine
      run: |
        npm install -g yarn
        cd assets
        yarn install
    - name: Verify application
      working-directory: apps/grapevine
      run: |
        cd assets
        yarn test
